const blog = {
  id: 7,
  title: "Dog threats Recall Alert ",
  slug: "Recently Recalled: Dog Treats Pulled From Shelves Over Salmonella Risk",
  headerImage: "../Dog.png",
  content: `
<p>
In recent weeks, there has been a significant development in the world of pet care,
specifically concerning the safety of dog treats that have been widely distributed across 
the United States. The recall of multiple bags of popular dog treats has been initiated 
due to the discovery of a potentially dangerous health risk that poses a threat not only 
to our beloved pets but to humans as well. Consumers Supply Distributing, LLC, a company 
headquartered in Iowa, was prompted to issue this recall following routine testing conducted by the U.S.
Food and Drug Administration (FDA). These tests detected the possible presence of salmonella, a type of bacteria 
that is frequently associated with foodborne illnesses and can lead to serious health issues. 

</p><br/>

<strong>Which Products Are Affected? </strong>

<p>
The recall specifically targets certain four-pound bags of dog biscuits that have become quite popular among pet owners.
Here are the details of the affected products: <br/> 
<strong> •	Country Vet Biscuits – Original Meaty Flavor</strong <br/> <br/>
o	UPC: 899623000463  <br/>
o	Lot Code: 40906513  <br/> 
conducted by the U.S. Food and Drug Administration (FDA). These tests detected the possible presence of salmonella, a type of bacteria that is frequently associated with foodborne illnesses and can lead to serious health issues. 
Which Products Are Affected? 
The recall specifically targets certain four-pound bags of dog biscuits that have become quite popular among pet owners. Here are the details of the affected products: 
<br/><strong>•	Country Vet Biscuits – Original Meaty Flavor</strong> <br/>
o	UPC: 899623000463 <br/>
o	Lot Code: 40906513 <br/>
o	Expiration Date: September 6, 2026 <br/>
<strong>•	Heartland Harvest Dog Biscuits </strong><br/>
o	UPC: 840227340691 <br/>
o	Lot Code: 40906513 <br/>
o	Expiration Date: September 6, 2026 <br/><br/>
These products were distributed to an extensive network of retail stores spanning several states, including Colorado, Iowa, Kansas, Missouri, Texas, Montana, and Nebraska. According to information provided by the FDA, the production and distribution of the affected lot have been halted as investigations are currently underway to ascertain the full extent of the contamination and prevent further distribution. 


<br/><br/>
<strong>Why This Recall Matters </strong><br />

Understanding the implications of this recall is crucial, as salmonella does not only pose a risk to humans — our pets are equally susceptible to becoming seriously ill. In dogs, the symptoms of salmonella infection can manifest in various forms, such as: <br/>
•	Lethargy and a noticeable decrease in energy <br/>
•	Diarrhea, which may sometimes include blood <br/>
•	Fever that may persist for several days <br/>
•	Vomiting, which can lead to dehydration <br/>
•	Abdominal pain or a noticeable loss of appetite <br/><br/>
It's important to note that even pets that appear healthy and show no outward signs of illness can still carry the bacteria. This means they can inadvertently pass it on to other animals or even to humans who come into contact with them.
For humans, a salmonella infection can begin to develop anywhere from 12 to 72 hours following exposure to contaminated products. The symptoms in humans typically last several days and can include diarrhea, fever, and stomach cramps. Certain groups of people are particularly vulnerable to severe illness, including children under the age of five, older adults, and individuals with weakened immune systems. The Centers for Disease Control and Prevention (CDC) has reported that salmonella is responsible for approximately 1.35 million illnesses, over 26,000 hospitalizations, and more than 400 deaths annually in the United States.  <br/>




  `,
  inlineImages: ["/recallHero.png"],
};

export default blog;
